### ISSUE TITLE
Filter not working if cell contains [ _

### ISSUE THREAD

**Issue by tomsx** [davidegironi/advanceddatagridview#2]
The filter in MenuStrip.cs is not working if a cell contains special characters like [ _.

with this change in MenuStrip.cs Row 614+615, it works just fine (needs some more testing)

                   foreach (TreeNodeItemSelector n in nodes)
                        sb.Append("'" + n.Value.ToString() + "'" + appx);
                    // OLD:  sb.Append("'" + FormatFilterString(n.Value.ToString()) + "'" + appx);

**Comment by davidegironi** [comment]
Hello, thank you for your feedback. I've fixed the FormatFilterString, check it out now and let me know, so i can close this issue.

**Comment by tomsx** [comment]
Hi, it's only partially fixed.

The following steps describe how to reproduce this behaviour.

In FormMain.cs, modify this line :

before:
`    i*2 % 3 == 0 ? null : i.ToString()+" str",`
after:
`     i*2 % 3 == 0 ? null : i.ToString()+" str [0000] ",`

run the application and
1) select any value from the filter list (column string). Result: filter works correctly now.
2) set a custom filter  (equals 0000). Result: no rows are shown

**Comment by davidegironi** [comment]
You have to select the "contains" filter in order to filter part of the string (LIKE), the "equals" filter check for all the string lenght (=).
2) if you set a custom filter (contains 0000), Result, all cells which contains 0000.
Hope this helps.
