### ISSUE TITLE
Filtering DateTime column causes StackOverflow Exception

### ISSUE THREAD

**Issue by will-scc** [davidegironi/advanceddatagridview#68]
The following is an example which can cause a StackOverflow Exception:

```
private void Form1_Load(object sender, EventArgs e)
{
    AdvancedDataGridView adgv = new AdvancedDataGridView
    {
        Dock = DockStyle.Fill
    };

    this.Controls.Add(adgv);

    DataTable dt = new DataTable();
    dt.Columns.Add("DateTime", typeof(DateTime));

    Random rand = new Random();

    for (int i = 0; i <= 10; i++)
    {
        int year = rand.Next(2010, 2020);
        int month = rand.Next(1, 12);
        int day = rand.Next(1, 28);

        object[] row = new object[]
        {
            new DateTime(year, month, day)
        };

        dt.Rows.Add(row);
    }

    BindingSource bs = new BindingSource();
    bs.DataSource = dt;
    adgv.DataSource = bs;
}
```

Simply attempting to uncheck a node will throw a `StackOverflow` exception. The overflow is occuring in the method `Zuby.ADGV.MenuStrip.SetNodesCheckState(Zuby.ADGV.TreeNodeItemSelector[], Boolean)`.

**Comment by davidegironi** [comment]
Thank you @will-scc for this feedback. Think I've got where is the problem. Let me check it in the next days.

**Comment by davidegironi** [comment]
Please check the update in code linked should fix it, and also contain the fix proposed by @kirsan31  here: 
https://file.re/2021/06/25/advanceddatagridview/ It will be automatically deleted in 24 hours, on 26 June 2021 at 17:06 (CET)

Below the code fix for this issue on MenuStrip.cs
```
        /// <summary>
        /// Check if filter buttons needs to be enabled
        /// </summary>
        private void CheckFilterButtonEnabled()
        {
            button_filter.Enabled = HasNodesChecked(_loadedNodes);
        }

        /// <summary>
        /// Check if selected nodes exists
        /// </summary>
        /// <param name="nodes"></param>
        /// <returns></returns>
        private bool HasNodesChecked(TreeNodeItemSelector[] nodes)
        {
            bool state = false;
            if (!String.IsNullOrEmpty(checkTextFilter.Text))
            {
                state = nodes.Any(n => n.CheckState == CheckState.Checked && n.Text.ToLower().Contains(checkTextFilter.Text.ToLower()));
            }
            else
            {
                state = nodes.Any(n => n.CheckState == CheckState.Checked);
            }

            if (state)
                return state;

            foreach (TreeNodeItemSelector node in nodes)
            {
                foreach (TreeNodeItemSelector nodesel in node.Nodes)
                {
                    state = HasNodesChecked(new TreeNodeItemSelector[] { nodesel });
                    if (state)
                        break;
                }
                if (state)
                    break;
            }

            return state;
        }
```

**Comment by davidegironi** [comment]
Hello.
Have you check this out?

**Comment by will-scc** [comment]
Hi Davide, sorry for the delay - I've been away.

With the above changes in `MenuStrip.cs` I am still getting a StackOverflow exception, but in `TreeNodeItemSelector` now, on the `CheckState` property now (I'm on a different PC with VS2019 rather than VS2017, so might be the same issue but with improved exception handling in VS2019):

```
public CheckState CheckState
{
    get
    {
        return _checkState;
    }
    set
    {
        _checkState = value;
        switch (_checkState)
        {
            case CheckState.Checked:
                StateImageIndex = 1;
                break;

            case CheckState.Indeterminate:
                StateImageIndex = 2;
                break;

            default:
                StateImageIndex = 0;
                break;
        }
    }
}
```

Based on my debugging the problem is that in `MenuStrip.SetNodesCheckState` we recursively call `SetNodesCheckState` passing in `_loadedNodes`. The problem is that `_loadedNodes` is never changed to remove any nodes so it is always all the nodes. This gets passed again and just keeps going until the stack runs out. 

For example, in this situation, there are 8 nodes:

![image](https://user-images.githubusercontent.com/31592644/124020677-7e50e880-d9e2-11eb-8405-37d2dccc90cc.png)

If I put some debug code in `SetNodeCheckState` to count the nodes in `_loadedNodes`:

```
if (node.Nodes != null && node.Nodes.Count > 0)
{
    loopCount += 1;
    Debug.WriteLine($"SetNodeCheckState: {_loadedNodes.Count()} (loop count: {loopCount}");
    SetNodesCheckState(_loadedNodes, isChecked);
}
```

It eventually crashes like this:

```
SetNodeCheckState: 8 (loop count: 7307)
SetNodeCheckState: 8 (loop count: 7308)
SetNodeCheckState: 8 (loop count: 7309)
SetNodeCheckState: 8 (loop count: 7310)
SetNodeCheckState: 8 (loop count: 7311)

Process is terminated due to StackOverflowException.
```

So either we are not meant to be passing in `_loadedNodes` but in fact the nodes of whatever was clicked or `_loadedNodes` is meant to decrease but that never happens. I'm not sure which is intended.

**Comment by davidegironi** [comment]
Thank you @will-scc for your check. It's not just the changed I've posted above in text format. Check the mod from the file download. You can find it here (the previous download was expired) https://www.file.io/download/PwereNkXmVbg

**Comment by will-scc** [comment]
Ah, I misunderstood.

The solution you linked looks good; all seems to be fixed regarding the Stack Overflow Exception. For the avoidance of doubt, I haven't tested anything else apart from confirming it no longer loops indefinitely when unchecking nodes and the filtering works for `DateTime` columns.

Thanks for your work on this Davide.

**Comment by davidegironi** [comment]
Thank you!
That would be enough. I've tested other things and all seems to work. Unluckily I've not developed this project in a TDD way.
I've release this update in nuget too.
